const COUNTRY_CODES = [
  { code: "+91", country: "India", iso: "in" },
  { code: "+1", country: "USA", iso: "us" },
  { code: "+44", country: "UK", iso: "gb" },
  { code: "+971", country: "UAE", iso: "ae" },
  { code: "+65", country: "Singapore", iso: "sg" },
  { code: "+61", country: "Australia", iso: "au" },
  { code: "+62", country: "Indonesia", iso: "id" },
  { code: "+66", country: "Thailand", iso: "th" },
  { code: "+81", country: "Japan", iso: "jp" },
  { code: "+82", country: "South Korea", iso: "kr" },
  { code: "+86", country: "China", iso: "cn" },
  { code: "+49", country: "Germany", iso: "de" },
  { code: "+33", country: "France", iso: "fr" },
  { code: "+39", country: "Italy", iso: "it" },
  { code: "+34", country: "Spain", iso: "es" },
  { code: "+31", country: "Netherlands", iso: "nl" },
  { code: "+46", country: "Sweden", iso: "se" },
  { code: "+41", country: "Switzerland", iso: "ch" },
  { code: "+43", country: "Austria", iso: "at" },
  { code: "+32", country: "Belgium", iso: "be" },
  { code: "+45", country: "Denmark", iso: "dk" },
  { code: "+47", country: "Norway", iso: "no" },
  { code: "+358", country: "Finland", iso: "fi" },
  { code: "+48", country: "Poland", iso: "pl" },
  { code: "+351", country: "Portugal", iso: "pt" },
  { code: "+353", country: "Ireland", iso: "ie" },
  { code: "+7", country: "Russia", iso: "ru" },
  { code: "+90", country: "Turkey", iso: "tr" },
  { code: "+966", country: "Saudi Arabia", iso: "sa" },
  { code: "+974", country: "Qatar", iso: "qa" },
  { code: "+973", country: "Bahrain", iso: "bh" },
  { code: "+968", country: "Oman", iso: "om" },
  { code: "+965", country: "Kuwait", iso: "kw" },
  { code: "+962", country: "Jordan", iso: "jo" },
  { code: "+961", country: "Lebanon", iso: "lb" },
  { code: "+20", country: "Egypt", iso: "eg" },
  { code: "+27", country: "South Africa", iso: "za" },
  { code: "+234", country: "Nigeria", iso: "ng" },
  { code: "+254", country: "Kenya", iso: "ke" },
  { code: "+255", country: "Tanzania", iso: "tz" },
  { code: "+256", country: "Uganda", iso: "ug" },
  { code: "+233", country: "Ghana", iso: "gh" },
  { code: "+212", country: "Morocco", iso: "ma" },
  { code: "+55", country: "Brazil", iso: "br" },
  { code: "+52", country: "Mexico", iso: "mx" },
  { code: "+54", country: "Argentina", iso: "ar" },
  { code: "+57", country: "Colombia", iso: "co" },
  { code: "+56", country: "Chile", iso: "cl" },
  { code: "+51", country: "Peru", iso: "pe" },
  { code: "+60", country: "Malaysia", iso: "my" },
  { code: "+63", country: "Philippines", iso: "ph" },
  { code: "+84", country: "Vietnam", iso: "vn" },
  { code: "+852", country: "Hong Kong", iso: "hk" },
  { code: "+853", country: "Macau", iso: "mo" },
  { code: "+886", country: "Taiwan", iso: "tw" },
  { code: "+880", country: "Bangladesh", iso: "bd" },
  { code: "+94", country: "Sri Lanka", iso: "lk" },
  { code: "+977", country: "Nepal", iso: "np" },
  { code: "+92", country: "Pakistan", iso: "pk" },
  { code: "+93", country: "Afghanistan", iso: "af" },
  { code: "+95", country: "Myanmar", iso: "mm" },
  { code: "+855", country: "Cambodia", iso: "kh" },
  { code: "+856", country: "Laos", iso: "la" },
  { code: "+64", country: "New Zealand", iso: "nz" },
  { code: "+679", country: "Fiji", iso: "fj" },
  { code: "+960", country: "Maldives", iso: "mv" },
  { code: "+248", country: "Seychelles", iso: "sc" },
  { code: "+230", country: "Mauritius", iso: "mu" },
  { code: "+385", country: "Croatia", iso: "hr" },
  { code: "+30", country: "Greece", iso: "gr" },
  { code: "+36", country: "Hungary", iso: "hu" },
  { code: "+420", country: "Czech Republic", iso: "cz" },
  { code: "+421", country: "Slovakia", iso: "sk" },
  { code: "+40", country: "Romania", iso: "ro" },
  { code: "+359", country: "Bulgaria", iso: "bg" },
  { code: "+380", country: "Ukraine", iso: "ua" },
  { code: "+370", country: "Lithuania", iso: "lt" },
  { code: "+371", country: "Latvia", iso: "lv" },
  { code: "+372", country: "Estonia", iso: "ee" },
  { code: "+354", country: "Iceland", iso: "is" },
  { code: "+356", country: "Malta", iso: "mt" },
  { code: "+357", country: "Cyprus", iso: "cy" },
  { code: "+352", country: "Luxembourg", iso: "lu" },
];

export default COUNTRY_CODES;
